- webstore-app/resources/deployment-cm.yaml
> VDS-34: Impement possibility to delete the applied purchase order number

- webstore-app/resources/deployment-cm.yaml
> VDS-70: Fix error. catalog - filters - id instead of text when select branch availability

- webstore-app/resources/deployment-cm.yaml
> VDS-99: Fix error. It is possible to pay an order using a credit card for non "Purchased agent" role

- webstore-app/resources/deployment-cm.yaml
a list view of collection page
> VDS-52, VDS-692: Fix errors with adding to cart and configure cases on..

- webstore-app/resources/deployment-cm.yaml
Variations on storefront should work (was broken) and variations widget should be hidden for configured products
> VDS-750: Fix variations

- webstore-app/resources/deployment-cm.yaml
- webstore-app/resources/kustomization.yaml
> VDS-789: Implement ability of bulk variations adding to cart

- webstore-app/resources/deployment-cm.yaml
- webstore-app/resources/kustomization.yaml
> VDS-789: Fix errors with bulk variations adding

- README.md
- common-base/platform-secrets.yaml
- webstore-app/overlays/dev/kustomization.yaml
- webstore-app/resources/deployment-cm.yaml
- webstore-app/resources/kustomization.yaml
- webstore-app/resources/platform-deploy.yaml
* Adding a variable that defines the vault URL 
https://virtocommerce.atlassian.net/browse/VCI-2
* Using new initial scripts
https://virtocommerce.atlassian.net/browse/VP-6712
> VCI-2: HA Vault

- common-base/platform-secrets.yaml
- webstore-app/overlays/demo/kustomization.yaml
- webstore-app/resources/deployment-cm.yaml
- webstore-app/resources/platform-deploy.yaml
* Adding a variable that defines the vault URL
https://virtocommerce.atlassian.net/browse/VCI-2
* Using new initial scripts
https://virtocommerce.atlassian.net/browse/VP-6712
> VCI-2: Configure vault and init platform

- common-base/public/platform-secrets.yaml
- public-app/deployment-cm.yaml
- public-app/kustomization.yaml
- public-app/platform-deploy.yaml
*Adding a variable that defines the vault URL
https://virtocommerce.atlassian.net/browse/VCI-2
*Using new initial scripts
https://virtocommerce.atlassian.net/browse/VP-6712
> VCI-2: Public

- webstore-app/resources/deployment-cm.yaml
- webstore-app/resources/kustomization.yaml
Workaround for https://virtocommerce.atlassian.net/browse/VP-4867 excluded:
1. We never faced this issue with validation
2. It causes code smells in Sonar
> VDS-867: Merge storefront & themes original dev

- apps-config/overlays/demo/public-app.yaml
- apps-config/overlays/demo/webstore-app.yaml
- public-app/traefik/ingress-https.yaml
- public-app/traefik/ingress.yaml
- webstore-app/resources/ingress-https.yaml
- webstore-app/resources/ingress.yaml
VCI-1: Add rate limits
VCI-19: Add notifications
> VDS-1032: Demo infra features

- common-base/deployment-cm.yaml
- common-base/platform-deploy.yaml
- common-base/storefront-deploy.yaml
- webstore-app/resources/deployment-cm.yaml
- webstore-app/resources/platform-deploy.yaml
- webstore-app/resources/storefront-deploy.yaml
Split deployment-cm
Add Init storefront
> VDS-1161: Configure init storefront

- common-base/deployment-cm.yaml
- webstore-app/resources/deployment-cm.yaml
> VDS-1210 Add VirtoCommerce.SimpleExportImport module

- webstore-app/resources/deployment-cm.yaml
> VDS-1193: QA-Test: Import file preview

- webstore-app/resources/deployment-cm.yaml
Include fixes for VDS-1226, VDS-1227, VDS-1228
> VDS-1207, VDS-1187: Create prices from csv

- webstore-app/resources/deployment-cm.yaml
https://virtocommerce.atlassian.net/browse/PT-982
> PT-982: Currency list blade is broken

- webstore-app/resources/deployment-cm.yaml
> VDS-1202 VDS-1249 Create new lines and Update existent lines with import; Update existent lines with import

- webstore-app/resources/deployment-cm.yaml
Need a smoke testing of the simple export/import
Also the empty report shuold be removed needs to be tested.
> VDS-1433 VDS-1447 VDS-1484 Refactoring of Csv Importer

- webstore-app/resources/deployment-cm.yaml
- webstore-app/resources/platform-cm.yaml
Check empty report shuld be removed also.
> VDS-1433 VDS-1447 VDS-1484 Simple import refactoring.

- webstore-app/resources/deployment-cm.yaml
https://user-images.githubusercontent.com/13153256/111497508-361efa80-8752-11eb-8f4f-747b5b1d1b7b.png
> VDS-1518 QA-Test: Migrate order details page

- webstore-app/overlays/demo/platform-overlay.env
- webstore-app/resources/deployment-cm.yaml
> VDS-1398 VDS-1405 VDS-1526 Export filtered and inside org. Lines limit..

- webstore-app/resources/deployment-cm.yaml
Create/update
Without errors report
> VDS-1318 VDS-1338 Implement organizations import

- webstore-app/resources/kustomization.yaml
This reverts commit 84499ff20f94686c070dd464847cdd1f407502e8.
> Revert "Automated update vc-demo-xapi-app from PR 37"
